wikis:
  enabled: false

projects:
  enabled: false

pullRequests:
  mergeCommitsEnabled: false
  squashMergingEnabled: true
  rebaseMergingEnabled: false
  autoMergeEnabled: true
  deleteBranchOnMergeEnabled: true

defaultBranchProtection:
  administratorsIncluded: true
  forcePushesAllowed: false
