name: Safe settings
description: Set project settings from .github/safe-settings.yml file

inputs:
  githubToken:
    required: true
    description: GitHub access token with at least 'public_repo' (use 'repo' scope instead of 'public_repo' for private repositories)
  settingsRef:
    required: false
    description: Git branch or tag where settings file should be taken from. Default branch is used by default.

runs:
  using: node12
  main: 'dist/index.js'
